
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
       context: ./requirements/nginx/
    env_file: ../.env
    ports:
      - '443:443'
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/wordpress
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
       context: .
       dockerfile: requirements/mariadb/Dockerfile
    env_file: ../.env
    ports:
      - '3306:3306'
    networks:
      - inception
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql/
    secrets:
      - db_creds
      - db_root

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
       context: ./requirements/wordpress/
    env_file: ../.env
    ports:
      - '9000:9000'
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/wordpress
    secrets:
      - db_creds 
      - wp_creds 
    depends_on:
      - mariadb


  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - inception
    container_name: portainer
    restart: on-failure
    ports:
      - "1313:9000"  # Portainer UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    # environment:
    #   TZ: "Your/Timezone"  # Optional: Replace with your timezone (e.g., "Etc/UTC" or "America/New_York")


  # adminer:
  #   image: adminer
  #   restart: on-failure
  #   networks:
  #     - inception
  #   ports:
  #     - 8080:8080

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb-data:
  # wordpress-data:
  portainer_data:

  # mariadb-data:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: ${DATA_PATH}/mariadb-data
  #   name: mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $HOME/data/wordpress-data
    name: wordpress


secrets:
  db_creds:
    file: /home/vfedorov/project/secrets/db_creds.txt
  db_root:
    file: /home/vfedorov/project/secrets/db_root_pass.txt
  wp_creds:
    file: /home/vfedorov/project/secrets/wp_creds.txt
