version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
       context: ./requirements/nginx
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
       context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql/

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
       context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - mariadb

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/mariadb-data
    name: mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH}/wordpress-data
    name: wordpress

secrets:
  db_creds:
    file: ${secrets_dir}/db_creds.txt
  db_root:
    file: ${secrets_dir}/db_root_pass.txt
  wp_creds:
    file: ${secrets_dir}/wp_creds.txt
