
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
       context: .
       dockerfile: requirements/nginx/Dockerfile
    env_file: ../.env
    ports:
      - '443:443'
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
       context: .
       dockerfile: requirements/mariadb/Dockerfile
    env_file: ../.env
    ports:
      - '3306:3306'
    environment:
        MARIADB_ROOT_PASSWORD: your-secure-password
    networks:
      - inception
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql/
    secrets:
      - db_creds
      - db_root

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
       context: .
       dockerfile: requirements/wordpress/Dockerfile
    env_file: ../.env
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    secrets:
      - db_creds
      - db_root
    depends_on:
      - mariadb

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb-data:
  wordpress-data:
  # mariadb-data:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: ${DATA_PATH}/mariadb-data
  #   name: mariadb
  # wordpress-data:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: ${DATA_PATH}/wordpress-data
  #   name: wordpress

secrets:
  db_creds:
    file: ${secrets_dir}/db_creds.txt
  db_root:
    file: ${secrets_dir}/db_root_pass.txt
  wp_creds:
    file: ${secrets_dir}/wp_creds.txt
